# DL Survival - Readmission time
 Updated 25/11/21

In [146]:
import pandas as pd
import numpy as np
import math
import statistics
from datetime import datetime
import datetime as dt
from datetime import timedelta
import json
import miceforest as mf

pd.set_option('display.max_columns', None)

## 1. Data cleaning

- Import MIMIC III combined data
- Review column unique values, assign correct data types
- Impute missing values

### 1.1: Importing data

In [147]:
df = pd.read_csv('../mimiciii_v2.csv')
print(df.shape)
df.head(5)

(6556, 123)

,subject_id,hadm_id,stay_id,age,gender,ethnicity,height,weight,admission_type,admission_location,admittime,dischtime,intime,outtime,insurance,marital_status,language,icustay_seq,los,first_careunit,last_careunit,dbsource,hospital_expire_flag,deathtime,dod,sofa,postop_intime,cabg,aortic,mitral,tricuspid,pulmonary,aki,ph,bicarb,baseexcess,chloride,free_calcium,glucose,potassium,sodium,lactate,hematocrit,hb,pco2,po2,bg_temp,fio2,ventrate,tidalvol,aado2,specimen,neutrophils,lymphocytes,wcc,plt,crp,albumin,creatinine,bun,magnesium,alt,alp,ast,ggt,bilirubin_total,bilirubin_direct,bilirubin_indirect,inr,fibrinogen,bleed_time,ptt,pt,hba1c,prbc,plts,ffp,cryo,mi,arrhythmia,ccf,pvd,cvd,dementia,copd,rheum,pud,liver_mild,diab_un,diab_cc,t1dm,t2dm,paraplegia,ckd,malig,liver_severe,met_ca,aids,smoking,dtoutput,echo,fluid,infection,intropes,insulin,pasp,padp,mpap,readmissions,readmit_times,first_readmission,vent_array,reintubation,reint_time,ext_time,hr,sbp,dbp,meanbp,rr,temp,spo2,cardiac_index
0,28772,132385,293560,19,F,white,170.18,115.4,EMERGENCY,EMERGENCY ROOM ADMIT,2148-12-15T00:19:00,2149-01-04T15:45:00,2148-12-23T13:00:34,2148-12-24T16:42:20,Private,SINGLE,ENGL,2,1.1540,CSRU,CSRU,carevue,0,NaN,NaN,2,2148-12-23T15:00:00,0,0,1,0,0,"[{'charttime': '2148-12-23T15:35:00', 'aki_sta...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...",[],[],"[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...",[],[],[],[],[],[],[],[],"[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...",[],[],"[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-24T02:47:00', 'value':...",[],[],[],[],[],[],[],"[{'charttime': '2148-12-23T15:52:00', 'value':...",[],[],"[{'charttime': '2148-12-23T15:52:00', 'value':...",[],"[{'charttime': '2148-12-20T14:20:00', 'value':...",[],[],[],[],0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2148-12-23T15:35:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2148-12-23T14:35:00', 'endtime...",[{'suspected_infection_time': '2148-12-20T12:2...,[],[],[],"[{'charttime': '2148-12-23T15:35:00', 'PADP': ...","[{'charttime': '2148-12-23T15:35:00', 'mPAP': ...",NaN,[],NaN,"[{'starttime': '2148-12-23T15:00:00', 'endtime...",0,NaN,2148-12-23 18:00:00,"[{'charttime': '2148-12-23T15:35:00', 'value':...","[{'charttime': '2148-12-23T16:00:00', 'value':...","[{'charttime': '2148-12-23T16:00:00', 'value':...","[{'charttime': '2148-12-23T15:35:00', 'value':...","[{'charttime': '2148-12-23T15:00:00', 'value':...","[{'charttime': '2148-12-23T15:45:00', 'value':...","[{'charttime': '2148-12-23T16:00:00', 'value':...","[{'charttime': '2148-12-23T15:45:00', 'ci': 2...."
1,73457,184405,251108,21,F,hispanic,152.40,60.0,ELECTIVE,PHYS REFERRAL/NORMAL DELI,2198-12-28T12:00:00,2199-01-04T20:05:00,2198-12-28T10:37:23,2198-12-29T10:14:22,Medicaid,SINGLE,ENGL,1,0.9840,CSRU,CSRU,metavision,0,NaN,NaN,6,2198-12-28T13:00:00,0,0,1,0,0,"[{'charttime': '2198-12-28T13:59:00', 'aki_sta...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...",[],[],[],[],[],[],[],[],"[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-28T13:59:00', 'value':...",[],[],"[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-29T02:12:00', 'value':...",[],[],[],[],[],[],[],"[{'charttime': '2198-12-28T13:59:00', 'value':...",[],[],"[{'charttime': '2198-12-28T13:59:00', 'value':...",[],[],"[{'charttime': '2198-12-28T15:12:00', 'bloodpr...",[],[],[],0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2198-12-28T13:45:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2198-12-28T12:45:00', 'endtime...",[{'suspected_infection_time': '2198-12-28T13:5...,"[{'starttime': '2198-12-28T13:55:00', 'endtime...",[],"[{'charttime': '2198-12-28T13:47:00', 'PASP': ...","[{'charttime': '2198-12-28T13:47:00', 'PADP': ...","[{'charttime': '2198-12-28T13:47:00', 'mPAP': ...",NaN,[],NaN,"[{'starttime': '2198-12-28T13:00:00', 'endtime...",0,NaN,2198-12-28 18:50:00,[],[],[],[],[],[],[],[]
2,93887,137808,242592,21,F,hispanic,160.02,74.4,ELECTIVE,PHYS REFERRAL/NORMAL DELI,2188-02-04T00:39:00,2188-02-09T16:41:00,2188-02-05T11:15:53,2188-02-07T18:14:19,Medicaid,SINGLE,ENGL,1,2.2906,CSRU,CSRU,metavision,0,NaN,NaN,2,2188-02-05T16:40:00,0,0,0,1,0,"[{'charttime': '2188-02-05T17:00:00', 'aki_sta...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...",[],[],"[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...",[],[],[],[],[],[],[],[],"[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...",[],[],"[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-06T03:19:00', 'value':...",[],[],[],[],[],[],[],"[{'charttime': '2188-02-05T17:00:00', 'value':...",[],[],"[{'charttime': '2188-02-05T17:00:00', 'value':...",[],"[{'charttime': '2188-01-16T07:05:00', 'value':...","[{'charttime': '2188-02-07T14:10:00', 'bloodpr...",[],[],[],0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2188-02-05T17:01:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2188-02-05T15:36:00', 'endtime...",[{'suspected_infection_time': '2188-02-04T22:4...,"[{'starttime': '2188-02-05T16:35:00', 'endtime...",[],[],[],[],NaN,[],NaN,"[{'starttime': '2188-02-05T16:40:00', 'endtime...",0,NaN,2188-02-05 21:00:00,[],[],[],[],[],[],[],[]
3,16927,109148,254842,22,M,white,190.50,71.1,EMERGENCY,EMERGENCY ROOM ADMIT,2166-09-24T20:15:00,2166-10-20T13:30:00,2166-10-06T09:41:05,2166-10-07T17:19:43,Private,SINGLE,NaN,2,1.3185,CSRU,CSRU,carevue,0,NaN,NaN,5,2166-10-06T11:30:00,0,1,1,0,0,"[{'charttime': '2166-10-06T03:48:00', 'aki_sta...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...",[],[],"[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...",[],[],[],[],[],[],[],[],"[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...",[],[],"[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T17:59:00', 'value':...",[],[],[],[],[],[],[],"[{'charttime': '2166-10-06T11:53:00', 'value':...",[],[],"[{'charttime': '2166-10-06T11:53:00', 'value':...",[],[],"[{'charttime': '2166-10-07T00:30:00', 'bloodpr...",[],[],[],0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2166-10-06T11:30:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2166-09-27T15:00:00', 'endtime...",[{'suspected_infection_time': '2166-09-24T11:1...,"[{'starttime': '2166-10-06T11:30:00', 'endtime...",[],[],"[{'charttime': '2166-10-06T11:30:00', 'PADP': ...","[{'charttime': '2166-10-06T11:30:00', 'mPAP': ...",NaN,[],NaN,"[{'starttime': '2166-10-06T11:30:00', 'endtime...",0,NaN,2166-10-06 14:11:00,"[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T12:00:00', 'ci': 5...."
4,4846,154439,264181,22,M,asian,182.88,66.0,ELECTIVE,PHYS REFERRAL/NORMAL DELI,2111-10-05T07:15:00,2111-10-13T15:30:00,2111-10-05T13:02:50,2111-10-09T10:13:52,Private,SINGLE,NaN,1,3.8827,CSRU,CSRU,carevue,0,NaN,NaN,7,2111-10-05T14:00:00,0,0,1,0,0,"[{'charttime': '2111-10-05T14:30:00', 'aki_sta...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...",[],"[{'charttime': '2111-10-07T09:11:00', 'value':...","[{'charttime': '2111-10-06T03:10:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-06T11:26:00', 'value':...",[],[],[],[],[],[],[],"[{'charttime': '2111-10-06T03:10:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...",[],[],"[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-07T02:09:00', 'value':...",[],[],[],[],[],[],[],"[{'charttime': '2111-10-05T14:44:00', 'value':...",[],[],"[{'charttime': '2111-10-05T14:44:00', 'value':...",[],"[{'charttime': '2111-09-29T12:00:00', 'value':...",[],[],[],[],0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2111-10-05T15:00:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2111-10-05T13:30:00', 'endtime...","[{'suspected_infection_time': None, 'antibioti...","[{'starttime': '2111-10-05T16:15:00', 'endtime...",[],[],"[{'charttime': '2111-10-05T14:15:00', 'PADP': ...","[{'charttime': '2111-10-05T14:15:00', 'mPAP': ...",NaN,[],NaN,"[{'starttime': '2111-10-05T14:00:00', 'endtime...",0,NaN,2111-10-05 17:15:00,"[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:00:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'ci': 3...."

#### 1.1.1: Column lists

In [148]:
print(df.columns.tolist())

['subject_id', 'hadm_id', 'stay_id', 'age', 'gender', 'ethnicity', 'height', 'weight', 'admission_type', 'admission_location', 'admittime', 'dischtime', 'intime', 'outtime', 'insurance', 'marital_status', 'language', 'icustay_seq', 'los', 'first_careunit', 'last_careunit', 'dbsource', 'hospital_expire_flag', 'deathtime', 'dod', 'sofa', 'postop_intime', 'cabg', 'aortic', 'mitral', 'tricuspid', 'pulmonary', 'aki', 'ph', 'bicarb', 'baseexcess', 'chloride', 'free_calcium', 'glucose', 'potassium', 'sodium', 'lactate', 'hematocrit', 'hb', 'pco2', 'po2', 'bg_temp', 'fio2', 'ventrate', 'tidalvol', 'aado2', 'specimen', 'neutrophils', 'lymphocytes', 'wcc', 'plt', 'crp', 'albumin', 'creatinine', 'bun', 'magnesium', 'alt', 'alp', 'ast', 'ggt', 'bilirubin_total', 'bilirubin_direct', 'bilirubin_indirect', 'inr', 'fibrinogen', 'bleed_time', 'ptt', 'pt', 'hba1c', 'prbc', 'plts', 'ffp', 'cryo', 'mi', 'arrhythmia', 'ccf', 'pvd', 'cvd', 'dementia', 'copd', 'rheum', 'pud', 'liver_mild', 'diab_un', 'diab_cc', 't1dm', 't2dm', 'paraplegia', 'ckd', 'malig', 'liver_severe', 'met_ca', 'aids', 'smoking', 'dtoutput', 'echo', 'fluid', 'infection', 'intropes', 'insulin', 'pasp', 'padp', 'mpap', 'readmissions', 'readmit_times', 'first_readmission', 'vent_array', 'reintubation', 'reint_time', 'ext_time', 'hr', 'sbp', 'dbp', 'meanbp', 'rr', 'temp', 'spo2', 'cardiac_index']

In [149]:
# removing columns

# removing spurious stay_id_X columns
df = df[[i for i in df.columns if i not in [f'stay_id_{i}' for i in range(1,15)]]]

# removing hospital_expire_flag as it is just a bool of whether deathtime is present
df = df[[i for i in df.columns if i != 'hospital_expire_flag']]

In [150]:
#view and reorder columns
colCats = {
    'admInfo': ['subject_id', 'hadm_id', 'stay_id'],
    'ptInfoCont': ['age', 'height', 'weight'],
    'demographics': ['gender','ethnicity','marital_status','insurance','language'],
    'admCat': ['first_careunit','last_careunit','admission_location','admission_type', 'dbsource'],
    'admTime': ['admittime', 'dischtime', 'intime', 'outtime', 'reint_time', 'ext_time', 'postop_intime', 'deathtime', 'dod'],
    'admNum': ['los','icustay_seq'],
    'markersTs': ['aki', 'ph', 'bicarb', 'baseexcess', 'chloride', 'free_calcium', 'glucose', 'potassium', 'sodium', 'lactate', 
                  'hematocrit', 'hb', 'pco2', 'po2', 'bg_temp', 'fio2', 'ventrate', 'tidalvol', 'aado2', 'specimen', 'neutrophils', 
                  'lymphocytes', 'wcc', 'plt', 'crp', 'albumin', 'creatinine', 'bun', 'magnesium', 'alt', 'alp', 'ast', 'ggt', 
                  'bilirubin_total', 'bilirubin_direct', 'bilirubin_indirect', 'inr', 'fibrinogen', 'bleed_time', 'ptt', 'pt', 'hba1c', 'prbc', 'plts', 'ffp', 'cryo'],
    'procedureType': ['aortic','mitral','tricuspid','pulmonary','cabg'],
    'comorbids': ['liver_severe','liver_mild','rheum','cvd','aids','ckd','copd','arrhythmia','pud','smoking','pvd',
                      'paraplegia','ccf','met_ca','t2dm','t1dm','malig','mi','dementia'],
    'diabUnits': ['diab_un', 'diab_cc'],
    'otherTs': ['dtoutput', 'echo', 'fluid', 'infection', 'intropes', 'insulin', 'pasp', 'padp', 'mpap', 'vent_array'],
    'vitalsTs': ['hr', 'sbp', 'dbp', 'meanbp', 'rr', 'temp', 'spo2', 'cardiac_index'],
    'misc': ['sofa', 'reintubation'],
    'readmitInfo': ['readmit_times', 'readmissions', 'first_readmission']
}
colCatsSquashed = [j for k in [colCats[i] for i in colCats] for j in k]

#print uncategorised and/or unaccounted columns
print([i for i in df.columns if i not in colCatsSquashed])
print([i for i in colCatsSquashed if i not in df.columns])

df[[i for i in df.columns if i not in colCatsSquashed]].head(5)

timeseries=[i for i in [*colCats['markersTs'],*colCats['vitalsTs'],*colCats['otherTs']] if i not in ('vent_array', 'fluid', 'infection', 'intropes', 'echo', 'aki')]
    
timeseries_valuenames = {'cardiac_index':'ci',
                         'plts':'bloodproduct',
                         'ffp':'bloodproduct',
                         'insulin':'amount',
                         'cryo':'bloodproduct',
                         'prbc':'bloodproduct',
                         'dtoutput':'output',
                         'pasp': 'PASP',
                         'padp': 'PADP',
                         'mpap': 'mPAP'
                        }

[]
[]

### 1.2: Cleaning data types

#### 1.2.0: NaN assignment

In [151]:
df = df.replace('NaT',np.datetime64('NaT'))
df = df.replace(['[]','NaN',np.datetime64('NaT')],np.NaN)

#### 1.2.1: Datetime columns

In [152]:
# set column types as datetime
for col in colCats['admTime']:
    df[col] = pd.to_datetime(df[col], format='%Y-%m-%dT%H:%M:%S')

In [153]:
## CHECK FOR ROWS WHERE DEATHTIME < INTIME OR ADMITTIME
# TODO AGAIN

#### 1.2.2: Demographics

In [154]:
for x in colCats['demographics']:
    print(x,': ',df[x].unique())

gender :  ['F' 'M']
ethnicity :  ['white' 'hispanic' 'asian' 'unknown' 'black' 'other' 'native']
marital_status :  ['SINGLE' 'MARRIED' 'DIVORCED' nan 'SEPARATED' 'UNKNOWN (DEFAULT)'
 'WIDOWED' 'LIFE PARTNER']
insurance :  ['Private' 'Medicaid' 'Government' 'Medicare' 'Self Pay']
language :  ['ENGL' nan 'SPAN' 'PORT' 'CANT' 'CAPE' 'PTUN' 'THAI' 'RUSS' 'PERS' 'GERM'
 'HAIT' 'MAND' 'VIET' 'ETHI' 'ARAB' 'ALBA' 'CAMB' 'HIND' '*BEN' 'AMER'
 'KORE' '*GUJ' 'GREE' 'ITAL' 'POLI' 'URDU' '*LEB' 'TURK' 'JAPA' '*ARM'
 '*FIL']

In [155]:
#ethnicity
df.replace({'ethnicity':
                {'unknown': np.NaN,'UNKNOWN':np.NaN,'UNABLE TO OBTAIN':np.NaN,
                'OTHER':'other','WHITE':'white','BLACK/AFRICAN AMERICAN':'black','ASIAN':'asian',
                'HISPANIC/LATINO':'hispanic','AMERICAN INDIAN/ALASKA NATIVE':'native'
                }
            }, 
            inplace=True)
print(df['ethnicity'].unique())

#marital_status
df.replace({'marital_status':
                {'UNKNOWN (DEFAULT)': np.NaN
                }
            }, 
            inplace=True)
print(df['marital_status'].unique())

#language
df.replace({'language':
                {'ENGLISH':'ENGL','?':np.NaN
                }
            }, 
            inplace=True)
print(df['language'].unique())

['white' 'hispanic' 'asian' nan 'black' 'other' 'native']
['SINGLE' 'MARRIED' 'DIVORCED' nan 'SEPARATED' 'WIDOWED' 'LIFE PARTNER']
['ENGL' nan 'SPAN' 'PORT' 'CANT' 'CAPE' 'PTUN' 'THAI' 'RUSS' 'PERS' 'GERM'
 'HAIT' 'MAND' 'VIET' 'ETHI' 'ARAB' 'ALBA' 'CAMB' 'HIND' '*BEN' 'AMER'
 'KORE' '*GUJ' 'GREE' 'ITAL' 'POLI' 'URDU' '*LEB' 'TURK' 'JAPA' '*ARM'
 '*FIL']

#### 1.2.3: ✔Procedure type

In [156]:
for x in colCats['procedureType']:
    print(x,': ',df[x].unique())

aortic :  [0 1]
mitral :  [1 0]
tricuspid :  [0 1]
pulmonary :  [0 1]
cabg :  [0 1]

#### 1.2.5: ✔Comorbidities

In [157]:
for x in colCats['comorbids']:
    print(x,': ',df[x].unique())

liver_severe :  [0 1]
liver_mild :  [0 1]
rheum :  [0 1]
cvd :  [0 1]
aids :  [0 1]
ckd :  [0 1]
copd :  [0 1]
arrhythmia :  [1 0]
pud :  [0 1]
smoking :  [0 1]
pvd :  [0 1]
paraplegia :  [0 1]
ccf :  [0 1]
met_ca :  [0 1]
t2dm :  [0]
t1dm :  [0]
malig :  [0 1]
mi :  [0 1]
dementia :  [0 1]

#### 1.2.6: Admissions (categorical)

In [158]:
for x in colCats['admCat']:
    print(x,': ',df[x].unique())

first_careunit :  ['CSRU' 'CCU' 'MICU' 'SICU' 'TSICU']
last_careunit :  ['CSRU' 'SICU' 'MICU' 'CCU' 'TSICU']
admission_location :  ['EMERGENCY ROOM ADMIT' 'PHYS REFERRAL/NORMAL DELI'
 'TRANSFER FROM HOSP/EXTRAM' 'CLINIC REFERRAL/PREMATURE'
 'TRANSFER FROM OTHER HEALT' 'TRANSFER FROM SKILLED NUR']
admission_type :  ['EMERGENCY' 'ELECTIVE' 'URGENT']
dbsource :  ['carevue' 'metavision' 'both']

#### 1.2.7: Others

In [159]:
# for x in others:
#     print(x,': ',df[x].unique())

### 1.3: Parsing time series data

In [160]:
hoursRange = 24

In [161]:
def va_parser(row):
    """
    Takes row from `df` returns a list of starttime, endtime, vent duration 
    for first and (if applicable) second intubations
    
    Returns
        0 int_time1: first intubation starttime
        1 ext_time1: first intubation endtime
        2 duration1: first intubation duration
        3 int_time2: second intubation starttime
        4 ext_time2: second intubation endtime 
        5 duration2: second intubation duration
    """
    [int_time1, ext_time1, duration1, int_time2, ext_time2, duration2] = [np.NaN for i in range(6)]
    value = row['vent_array']
    if value == np.NaN or pd.isna(value):
        return [np.NaN for i in range(6)]
    
    a = value.replace("'",'"')
    a = a.replace('\n ...\n',',').replace('\n', ',').replace('...', '')
    a = a.replace('),', ')",')
    a = json.loads(a)
    b = [(i['starttime'], i['endtime'], i['duration_hours']) for i in a]
    int_time1=dt.datetime.strptime(b[0][0],'%Y-%m-%dT%H:%M:%S')
    ext_time1=dt.datetime.strptime(b[0][0],'%Y-%m-%dT%H:%M:%S')
    duration1=float(b[0][2])
    
    if len(b)>=2:
        int_time2=dt.datetime.strptime(b[1][0],'%Y-%m-%dT%H:%M:%S')
        ext_time2=dt.datetime.strptime(b[1][1],'%Y-%m-%dT%H:%M:%S')
        duration2=float(b[1][2])
    
    return int_time1, ext_time1, duration1, int_time2, ext_time2, duration2

for col in ['int_time1', 'ext_time1', 'duration1', 'int_time2', 'ext_time2', 'duration2']:
    df[col] = np.zeros(df.shape[0])

for i in range(df.shape[0]):
    x = va_parser(df.loc[i])
    for i in range(6):
        df[['int_time1', 'ext_time1', 'duration1', 'int_time2', 'ext_time2', 'duration2'][i]] = x[i]

colCats['ventTimes'] = ['int_time1', 'ext_time1', 'duration1', 'int_time2', 'ext_time2', 'duration2']
df.head(5)

,subject_id,hadm_id,stay_id,age,gender,ethnicity,height,weight,admission_type,admission_location,admittime,dischtime,intime,outtime,insurance,marital_status,language,icustay_seq,los,first_careunit,last_careunit,dbsource,deathtime,dod,sofa,postop_intime,cabg,aortic,mitral,tricuspid,pulmonary,aki,ph,bicarb,baseexcess,chloride,free_calcium,glucose,potassium,sodium,lactate,hematocrit,hb,pco2,po2,bg_temp,fio2,ventrate,tidalvol,aado2,specimen,neutrophils,lymphocytes,wcc,plt,crp,albumin,creatinine,bun,magnesium,alt,alp,ast,ggt,bilirubin_total,bilirubin_direct,bilirubin_indirect,inr,fibrinogen,bleed_time,ptt,pt,hba1c,prbc,plts,ffp,cryo,mi,arrhythmia,ccf,pvd,cvd,dementia,copd,rheum,pud,liver_mild,diab_un,diab_cc,t1dm,t2dm,paraplegia,ckd,malig,liver_severe,met_ca,aids,smoking,dtoutput,echo,fluid,infection,intropes,insulin,pasp,padp,mpap,readmissions,readmit_times,first_readmission,vent_array,reintubation,reint_time,ext_time,hr,sbp,dbp,meanbp,rr,temp,spo2,cardiac_index,int_time1,ext_time1,duration1,int_time2,ext_time2,duration2
0,28772,132385,293560,19,F,white,170.18,115.4,EMERGENCY,EMERGENCY ROOM ADMIT,2148-12-15 00:19:00,2149-01-04 15:45:00,2148-12-23 13:00:34,2148-12-24 16:42:20,Private,SINGLE,ENGL,2,1.1540,CSRU,CSRU,carevue,NaT,NaT,2,2148-12-23 15:00:00,0,0,1,0,0,"[{'charttime': '2148-12-23T15:35:00', 'aki_sta...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...",NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...",NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-24T02:47:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...",NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...",NaN,"[{'charttime': '2148-12-20T14:20:00', 'value':...",NaN,NaN,NaN,NaN,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2148-12-23T15:35:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2148-12-23T14:35:00', 'endtime...",[{'suspected_infection_time': '2148-12-20T12:2...,NaN,NaN,NaN,"[{'charttime': '2148-12-23T15:35:00', 'PADP': ...","[{'charttime': '2148-12-23T15:35:00', 'mPAP': ...",NaN,NaN,NaN,"[{'starttime': '2148-12-23T15:00:00', 'endtime...",0,NaT,2148-12-23 18:00:00,"[{'charttime': '2148-12-23T15:35:00', 'value':...","[{'charttime': '2148-12-23T16:00:00', 'value':...","[{'charttime': '2148-12-23T16:00:00', 'value':...","[{'charttime': '2148-12-23T15:35:00', 'value':...","[{'charttime': '2148-12-23T15:00:00', 'value':...","[{'charttime': '2148-12-23T15:45:00', 'value':...","[{'charttime': '2148-12-23T16:00:00', 'value':...","[{'charttime': '2148-12-23T15:45:00', 'ci': 2....",2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN
1,73457,184405,251108,21,F,hispanic,152.40,60.0,ELECTIVE,PHYS REFERRAL/NORMAL DELI,2198-12-28 12:00:00,2199-01-04 20:05:00,2198-12-28 10:37:23,2198-12-29 10:14:22,Medicaid,SINGLE,ENGL,1,0.9840,CSRU,CSRU,metavision,NaT,NaT,6,2198-12-28 13:00:00,0,0,1,0,0,"[{'charttime': '2198-12-28T13:59:00', 'aki_sta...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-28T13:59:00', 'value':...",NaN,NaN,"[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-29T02:12:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2198-12-28T13:59:00', 'value':...",NaN,NaN,"[{'charttime': '2198-12-28T13:59:00', 'value':...",NaN,NaN,"[{'charttime': '2198-12-28T15:12:00', 'bloodpr...",NaN,NaN,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2198-12-28T13:45:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2198-12-28T12:45:00', 'endtime...",[{'suspected_infection_time': '2198-12-28T13:5...,"[{'starttime': '2198-12-28T13:55:00', 'endtime...",NaN,"[{'charttime': '2198-12-28T13:47:00', 'PASP': ...","[{'charttime': '2198-12-28T13:47:00', 'PADP': ...","[{'charttime': '2198-12-28T13:47:00', 'mPAP': ...",NaN,NaN,NaN,"[{'starttime': '2198-12-28T13:00:00', 'endtime...",0,NaT,2198-12-28 18:50:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN
2,93887,137808,242592,21,F,hispanic,160.02,74.4,ELECTIVE,PHYS REFERRAL/NORMAL DELI,2188-02-04 00:39:00,2188-02-09 16:41:00,2188-02-05 11:15:53,2188-02-07 18:14:19,Medicaid,SINGLE,ENGL,1,2.2906,CSRU,CSRU,metavision,NaT,NaT,2,2188-02-05 16:40:00,0,0,0,1,0,"[{'charttime': '2188-02-05T17:00:00', 'aki_sta...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...",NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...",NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-06T03:19:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...",NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...",NaN,"[{'charttime': '2188-01-16T07:05:00', 'value':...","[{'charttime': '2188-02-07T14:10:00', 'bloodpr...",NaN,NaN,NaN,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2188-02-05T17:01:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2188-02-05T15:36:00', 'endtime...",[{'suspected_infection_time': '2188-02-04T22:4...,"[{'starttime': '2188-02-05T16:35:00', 'endtime...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'starttime': '2188-02-05T16:40:00', 'endtime...",0,NaT,2188-02-05 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN
3,16927,109148,254842,22,M,white,190.50,71.1,EMERGENCY,EMERGENCY ROOM ADMIT,2166-09-24 20:15:00,2166-10-20 13:30:00,2166-10-06 09:41:05,2166-10-07 17:19:43,Private,SINGLE,NaN,2,1.3185,CSRU,CSRU,carevue,NaT,NaT,5,2166-10-06 11:30:00,0,1,1,0,0,"[{'charttime': '2166-10-06T03:48:00', 'aki_sta...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...",NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...",NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T17:59:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...",NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...",NaN,NaN,"[{'charttime': '2166-10-07T00:30:00', 'bloodpr...",NaN,NaN,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2166-10-06T11:30:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2166-09-27T15:00:00', 'endtime...",[{'suspected_infection_time': '2166-09-24T11:1...,"[{'starttime': '2166-10-06T11:30:00', 'endtime...",NaN,NaN,"[{'charttime': '2166-10-06T11:30:00', 'PADP': ...","[{'charttime': '2166-10-06T11:30:00', 'mPAP': ...",NaN,NaN,NaN,"[{'starttime': '2166-10-06T11:30:00', 'endtime...",0,NaT,2166-10-06 14:11:00,"[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T12:00:00', 'ci': 5....",2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN
4,4846,154439,264181,22,M,asian,182.88,66.0,ELECTIVE,PHYS REFERRAL/NORMAL DELI,2111-10-05 07:15:00,2111-10-13 15:30:00,2111-10-05 13:02:50,2111-10-09 10:13:52,Private,SINGLE,NaN,1,3.8827,CSRU,CSRU,carevue,NaT,NaT,7,2111-10-05 14:00:00,0,0,1,0,0,"[{'charttime': '2111-10-05T14:30:00', 'aki_sta...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...",NaN,"[{'charttime': '2111-10-07T09:11:00', 'value':...","[{'charttime': '2111-10-06T03:10:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-06T11:26:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2111-10-06T03:10:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...",NaN,NaN,"[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-07T02:09:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2111-10-05T14:44:00', 'value':...",NaN,NaN,"[{'charttime': '2111-10-05T14:44:00', 'value':...",NaN,"[{'charttime': '2111-09-29T12:00:00', 'value':...",NaN,NaN,NaN,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2111-10-05T15:00:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2111-10-05T13:30:00', 'endtime...","[{'suspected_infection_time': None, 'antibioti...","[{'starttime': '2111-10-05T16:15:00', 'endtime...",NaN,NaN,"[{'charttime': '2111-10-05T14:15:00', 'PADP': ...","[{'charttime': '2111-10-05T14:15:00', 'mPAP': ...",NaN,NaN,NaN,"[{'starttime': '2111-10-05T14:00:00', 'endtime...",0,NaT,2111-10-05 17:15:00,"[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:00:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'ci': 3....",2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN

In [162]:
def ts_parser(value, timeDelta=None, timeLimits=None, valuename='value'):
    '''
    # timeDelta is timedelta in hours from earliest entry
    # timeLimits = (startTime, endTime)
    # if both timeDelta and timeLimits are provided, timeDelta overrules.
    # if both are None, then all timepoints are accepted
    # returns arithmetic mean, max, min, first
    '''
    if value == np.NaN or pd.isna(value):
        return np.NaN, np.NaN, np.NaN, np.NaN
    a = value.replace("'", '"')
    a = a.replace('\n ...\n',',').replace('\n', ',').replace('...', '')
    a = a.replace('datetime.', '"dt.')
    a = a.replace(f'), "{valuename}"', f')", "{valuename}"')
    a = a.replace('"unit": None', '"unit": "None"')
    a = a.replace('starttime', 'charttime')
    a = json.loads(a)
    b = [(dt.datetime.strptime(i['charttime'],'%Y-%m-%dT%H:%M:%S'), i[valuename]) for i in a]
    
    if timeDelta:
        startTime = min(b, key=lambda x:x[0])[0]
        inc_b = [i[1] for i in b if i[0] <= startTime + dt.timedelta(hours=timeDelta)]
    else:
        if timeLimits:
            inc_b = [i[1] for i in b if i[0] >= timeLimits[0] and i[0] <= timeLimits[1]]
        else:
            inc_b = [i[1] for i in b]
    if len(inc_b) == 0:
        return np.NaN, np.NaN, np.NaN, np.NaN
    
    return sum(inc_b) / len(inc_b), max(inc_b), min(inc_b), sorted(inc_b)[0]

In [163]:
# delete all rows where int_time1 OR ext_time1 are missing ## NOTE: no need as postop_intime has now taken this bit over
df = df[~(pd.isnull(df['postop_intime']) | pd.isnull(df['outtime']))]
df = df.reset_index()
df.head(5)

,index,subject_id,hadm_id,stay_id,age,gender,ethnicity,height,weight,admission_type,admission_location,admittime,dischtime,intime,outtime,insurance,marital_status,language,icustay_seq,los,first_careunit,last_careunit,dbsource,deathtime,dod,sofa,postop_intime,cabg,aortic,mitral,tricuspid,pulmonary,aki,ph,bicarb,baseexcess,chloride,free_calcium,glucose,potassium,sodium,lactate,hematocrit,hb,pco2,po2,bg_temp,fio2,ventrate,tidalvol,aado2,specimen,neutrophils,lymphocytes,wcc,plt,crp,albumin,creatinine,bun,magnesium,alt,alp,ast,ggt,bilirubin_total,bilirubin_direct,bilirubin_indirect,inr,fibrinogen,bleed_time,ptt,pt,hba1c,prbc,plts,ffp,cryo,mi,arrhythmia,ccf,pvd,cvd,dementia,copd,rheum,pud,liver_mild,diab_un,diab_cc,t1dm,t2dm,paraplegia,ckd,malig,liver_severe,met_ca,aids,smoking,dtoutput,echo,fluid,infection,intropes,insulin,pasp,padp,mpap,readmissions,readmit_times,first_readmission,vent_array,reintubation,reint_time,ext_time,hr,sbp,dbp,meanbp,rr,temp,spo2,cardiac_index,int_time1,ext_time1,duration1,int_time2,ext_time2,duration2
0,0,28772,132385,293560,19,F,white,170.18,115.4,EMERGENCY,EMERGENCY ROOM ADMIT,2148-12-15 00:19:00,2149-01-04 15:45:00,2148-12-23 13:00:34,2148-12-24 16:42:20,Private,SINGLE,ENGL,2,1.1540,CSRU,CSRU,carevue,NaT,NaT,2,2148-12-23 15:00:00,0,0,1,0,0,"[{'charttime': '2148-12-23T15:35:00', 'aki_sta...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...",NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...","[{'charttime': '2148-12-23T15:58:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...",NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-23T15:52:00', 'value':...","[{'charttime': '2148-12-24T02:47:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...",NaN,NaN,"[{'charttime': '2148-12-23T15:52:00', 'value':...",NaN,"[{'charttime': '2148-12-20T14:20:00', 'value':...",NaN,NaN,NaN,NaN,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2148-12-23T15:35:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2148-12-23T14:35:00', 'endtime...",[{'suspected_infection_time': '2148-12-20T12:2...,NaN,NaN,NaN,"[{'charttime': '2148-12-23T15:35:00', 'PADP': ...","[{'charttime': '2148-12-23T15:35:00', 'mPAP': ...",NaN,NaN,NaN,"[{'starttime': '2148-12-23T15:00:00', 'endtime...",0,NaT,2148-12-23 18:00:00,"[{'charttime': '2148-12-23T15:35:00', 'value':...","[{'charttime': '2148-12-23T16:00:00', 'value':...","[{'charttime': '2148-12-23T16:00:00', 'value':...","[{'charttime': '2148-12-23T15:35:00', 'value':...","[{'charttime': '2148-12-23T15:00:00', 'value':...","[{'charttime': '2148-12-23T15:45:00', 'value':...","[{'charttime': '2148-12-23T16:00:00', 'value':...","[{'charttime': '2148-12-23T15:45:00', 'ci': 2....",2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN
1,1,73457,184405,251108,21,F,hispanic,152.40,60.0,ELECTIVE,PHYS REFERRAL/NORMAL DELI,2198-12-28 12:00:00,2199-01-04 20:05:00,2198-12-28 10:37:23,2198-12-29 10:14:22,Medicaid,SINGLE,ENGL,1,0.9840,CSRU,CSRU,metavision,NaT,NaT,6,2198-12-28 13:00:00,0,0,1,0,0,"[{'charttime': '2198-12-28T13:59:00', 'aki_sta...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...","[{'charttime': '2198-12-28T13:38:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-28T13:59:00', 'value':...",NaN,NaN,"[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-28T13:59:00', 'value':...","[{'charttime': '2198-12-29T02:12:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2198-12-28T13:59:00', 'value':...",NaN,NaN,"[{'charttime': '2198-12-28T13:59:00', 'value':...",NaN,NaN,"[{'charttime': '2198-12-28T15:12:00', 'bloodpr...",NaN,NaN,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2198-12-28T13:45:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2198-12-28T12:45:00', 'endtime...",[{'suspected_infection_time': '2198-12-28T13:5...,"[{'starttime': '2198-12-28T13:55:00', 'endtime...",NaN,"[{'charttime': '2198-12-28T13:47:00', 'PASP': ...","[{'charttime': '2198-12-28T13:47:00', 'PADP': ...","[{'charttime': '2198-12-28T13:47:00', 'mPAP': ...",NaN,NaN,NaN,"[{'starttime': '2198-12-28T13:00:00', 'endtime...",0,NaT,2198-12-28 18:50:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN
2,2,93887,137808,242592,21,F,hispanic,160.02,74.4,ELECTIVE,PHYS REFERRAL/NORMAL DELI,2188-02-04 00:39:00,2188-02-09 16:41:00,2188-02-05 11:15:53,2188-02-07 18:14:19,Medicaid,SINGLE,ENGL,1,2.2906,CSRU,CSRU,metavision,NaT,NaT,2,2188-02-05 16:40:00,0,0,0,1,0,"[{'charttime': '2188-02-05T17:00:00', 'aki_sta...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...",NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...","[{'charttime': '2188-02-05T17:07:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...",NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-05T17:00:00', 'value':...","[{'charttime': '2188-02-06T03:19:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...",NaN,NaN,"[{'charttime': '2188-02-05T17:00:00', 'value':...",NaN,"[{'charttime': '2188-01-16T07:05:00', 'value':...","[{'charttime': '2188-02-07T14:10:00', 'bloodpr...",NaN,NaN,NaN,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2188-02-05T17:01:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2188-02-05T15:36:00', 'endtime...",[{'suspected_infection_time': '2188-02-04T22:4...,"[{'starttime': '2188-02-05T16:35:00', 'endtime...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'starttime': '2188-02-05T16:40:00', 'endtime...",0,NaT,2188-02-05 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN
3,3,16927,109148,254842,22,M,white,190.50,71.1,EMERGENCY,EMERGENCY ROOM ADMIT,2166-09-24 20:15:00,2166-10-20 13:30:00,2166-10-06 09:41:05,2166-10-07 17:19:43,Private,SINGLE,NaN,2,1.3185,CSRU,CSRU,carevue,NaT,NaT,5,2166-10-06 11:30:00,0,1,1,0,0,"[{'charttime': '2166-10-06T03:48:00', 'aki_sta...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...",NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...","[{'charttime': '2166-10-06T12:01:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...",NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T11:53:00', 'value':...","[{'charttime': '2166-10-06T17:59:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...",NaN,NaN,"[{'charttime': '2166-10-06T11:53:00', 'value':...",NaN,NaN,"[{'charttime': '2166-10-07T00:30:00', 'bloodpr...",NaN,NaN,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2166-10-06T11:30:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2166-09-27T15:00:00', 'endtime...",[{'suspected_infection_time': '2166-09-24T11:1...,"[{'starttime': '2166-10-06T11:30:00', 'endtime...",NaN,NaN,"[{'charttime': '2166-10-06T11:30:00', 'PADP': ...","[{'charttime': '2166-10-06T11:30:00', 'mPAP': ...",NaN,NaN,NaN,"[{'starttime': '2166-10-06T11:30:00', 'endtime...",0,NaT,2166-10-06 14:11:00,"[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T11:30:00', 'value':...","[{'charttime': '2166-10-06T12:00:00', 'ci': 5....",2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN
4,4,4846,154439,264181,22,M,asian,182.88,66.0,ELECTIVE,PHYS REFERRAL/NORMAL DELI,2111-10-05 07:15:00,2111-10-13 15:30:00,2111-10-05 13:02:50,2111-10-09 10:13:52,Private,SINGLE,NaN,1,3.8827,CSRU,CSRU,carevue,NaT,NaT,7,2111-10-05 14:00:00,0,0,1,0,0,"[{'charttime': '2111-10-05T14:30:00', 'aki_sta...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...",NaN,"[{'charttime': '2111-10-07T09:11:00', 'value':...","[{'charttime': '2111-10-06T03:10:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-05T14:52:00', 'value':...","[{'charttime': '2111-10-06T11:26:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2111-10-06T03:10:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...",NaN,NaN,"[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-05T14:44:00', 'value':...","[{'charttime': '2111-10-07T02:09:00', 'value':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'charttime': '2111-10-05T14:44:00', 'value':...",NaN,NaN,"[{'charttime': '2111-10-05T14:44:00', 'value':...",NaN,"[{'charttime': '2111-09-29T12:00:00', 'value':...",NaN,NaN,NaN,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"[{'charttime': '2111-10-05T15:00:00', 'output'...","[{'CHARTTIME': None, 'STORETIME': None, 'CATEG...","[{'starttime': '2111-10-05T13:30:00', 'endtime...","[{'suspected_infection_time': None, 'antibioti...","[{'starttime': '2111-10-05T16:15:00', 'endtime...",NaN,NaN,"[{'charttime': '2111-10-05T14:15:00', 'PADP': ...","[{'charttime': '2111-10-05T14:15:00', 'mPAP': ...",NaN,NaN,NaN,"[{'starttime': '2111-10-05T14:00:00', 'endtime...",0,NaT,2111-10-05 17:15:00,"[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:00:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'value':...","[{'charttime': '2111-10-05T14:15:00', 'ci': 3....",2197-06-09 14:00:00,2197-06-09 14:00:00,5.283333,NaN,NaN,NaN

### 1.4: Handling missing data

#### 1.4.0 Assessing for missing data

In [164]:
def missing_values_table(df): 
    mis_val = df.isnull().sum()
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
    mis_val_table_ren_columns = mis_val_table.rename(columns = {0: 'Missing Values', 1: '% Missing Values'})
    return mis_val_table_ren_columns

missing_data = missing_values_table(df)

#set limit and get list of variables missing above limit in `missing_cols`
# missing_limit = 50 #allen
missing_limit = 70 #marcel
missing_cols = missing_data.loc[missing_data['% Missing Values']>missing_limit].index.tolist()
print(missing_cols)
missing_data = missing_data.loc[missing_data['% Missing Values']>missing_limit]
missing_data = missing_data.sort_values(by=['% Missing Values'])
pd.set_option('display.max_rows', None)
print(missing_data)
pd.reset_option('display.max_rows')

['deathtime', 'dod', 'bg_temp', 'fio2', 'ventrate', 'tidalvol', 'aado2', 'specimen', 'neutrophils', 'lymphocytes', 'crp', 'albumin', 'alt', 'alp', 'ast', 'ggt', 'bilirubin_total', 'bilirubin_direct', 'bilirubin_indirect', 'fibrinogen', 'bleed_time', 'pt', 'plts', 'ffp', 'cryo', 'insulin', 'readmissions', 'readmit_times', 'first_readmission', 'reint_time', 'int_time2', 'ext_time2', 'duration2']
                    Missing Values  % Missing Values
bg_temp                       4657         71.034167
fio2                          4768         72.727273
dod                           5145         78.477730
bilirubin_total               5299         80.826724
alt                           5315         81.070775
ast                           5318         81.116534
alp                           5337         81.406345
cryo                          5502         83.923124
insulin                       5502         83.923124
ffp                           5502         83.923124
tidalvol                      5563         84.853569
plts                          5568         84.929835
albumin                       5649         86.165345
fibrinogen                    5824         88.834655
lymphocytes                   5964         90.970104
neutrophils                   5964         90.970104
aado2                         6010         91.671751
reint_time                    6031         91.992068
first_readmission             6243         95.225747
readmissions                  6243         95.225747
readmit_times                 6243         95.225747
bilirubin_direct              6429         98.062843
bilirubin_indirect            6433         98.123856
deathtime                     6439         98.215375
crp                           6538         99.725442
ggt                           6548         99.877974
bleed_time                    6556        100.000000
ext_time2                     6556        100.000000
specimen                      6556        100.000000
ventrate                      6556        100.000000
int_time2                     6556        100.000000
pt                            6556        100.000000
duration2                     6556        100.000000

In [165]:
dfDroppedMissing = df[[i for i in df.columns if i not in missing_data.index and i not in ['duration2','int_time2','ext_time2','aado2','fio2','deathtime']]]
print(list(dfDroppedMissing.columns))

['index', 'subject_id', 'hadm_id', 'stay_id', 'age', 'gender', 'ethnicity', 'height', 'weight', 'admission_type', 'admission_location', 'admittime', 'dischtime', 'intime', 'outtime', 'insurance', 'marital_status', 'language', 'icustay_seq', 'los', 'first_careunit', 'last_careunit', 'dbsource', 'sofa', 'postop_intime', 'cabg', 'aortic', 'mitral', 'tricuspid', 'pulmonary', 'aki', 'ph', 'bicarb', 'baseexcess', 'chloride', 'free_calcium', 'glucose', 'potassium', 'sodium', 'lactate', 'hematocrit', 'hb', 'pco2', 'po2', 'wcc', 'plt', 'creatinine', 'bun', 'magnesium', 'inr', 'ptt', 'hba1c', 'prbc', 'mi', 'arrhythmia', 'ccf', 'pvd', 'cvd', 'dementia', 'copd', 'rheum', 'pud', 'liver_mild', 'diab_un', 'diab_cc', 't1dm', 't2dm', 'paraplegia', 'ckd', 'malig', 'liver_severe', 'met_ca', 'aids', 'smoking', 'dtoutput', 'echo', 'fluid', 'infection', 'intropes', 'pasp', 'padp', 'mpap', 'vent_array', 'reintubation', 'ext_time', 'hr', 'sbp', 'dbp', 'meanbp', 'rr', 'temp', 'spo2', 'cardiac_index', 'int_time1', 'ext_time1', 'duration1']

#### 1.4.1 Beginning imputation

In [166]:
dfForImpute = pd.DataFrame([0 for i in range(dfDroppedMissing.shape[0])])

# generating timeseries summary values
for column in timeseries:
    if column not in dfDroppedMissing.columns:
        continue
    x = timeseries_valuenames[column] if column in timeseries_valuenames else "value"
    meanList = []
    maxList = []
    minList = []
    for i in range(len(dfDroppedMissing[column])):
        inTime = dfDroppedMissing['postop_intime'][i].to_pydatetime()
        outTime = dfDroppedMissing['outtime'][i].to_pydatetime()
        y = ts_parser(dfDroppedMissing[column][i], timeLimits=(inTime, outtime), valuename=x)
        meanList.append(y[0])
        maxList.append(y[1])
        minList.append(y[2])
    dfForImpute[column+'_mean'] = meanList
    dfForImpute[column+'_max'] = maxList
    dfForImpute[column+'_min'] = minList
    dfForImpute = dfForImpute.copy()

dfForImpute = dfForImpute[[i for i in dfForImpute.columns if i not in (0, '0')]]
dfForImpute.head(5)

,ph_mean,ph_max,ph_min,bicarb_mean,bicarb_max,bicarb_min,baseexcess_mean,baseexcess_max,baseexcess_min,chloride_mean,chloride_max,chloride_min,free_calcium_mean,free_calcium_max,free_calcium_min,glucose_mean,glucose_max,glucose_min,potassium_mean,potassium_max,potassium_min,sodium_mean,sodium_max,sodium_min,lactate_mean,lactate_max,lactate_min,hematocrit_mean,hematocrit_max,hematocrit_min,hb_mean,hb_max,hb_min,pco2_mean,pco2_max,pco2_min,po2_mean,po2_max,po2_min,wcc_mean,wcc_max,wcc_min,plt_mean,plt_max,plt_min,creatinine_mean,creatinine_max,creatinine_min,bun_mean,bun_max,bun_min,magnesium_mean,magnesium_max,magnesium_min,inr_mean,inr_max,inr_min,ptt_mean,ptt_max,ptt_min,hba1c_mean,hba1c_max,hba1c_min,prbc_mean,prbc_max,prbc_min,hr_mean,hr_max,hr_min,sbp_mean,sbp_max,sbp_min,dbp_mean,dbp_max,dbp_min,meanbp_mean,meanbp_max,meanbp_min,rr_mean,rr_max,rr_min,temp_mean,temp_max,temp_min,spo2_mean,spo2_max,spo2_min,cardiac_index_mean,cardiac_index_max,cardiac_index_min,dtoutput_mean,dtoutput_max,dtoutput_min,pasp_mean,pasp_max,pasp_min,padp_mean,padp_max,padp_min,mpap_mean,mpap_max,mpap_min
0,7.352000,7.38,7.31,26.0,27.0,25.0,0.000000,2.0,-2.0,107.000000,109.0,105.0,1.215000,1.27,1.16,121.518519,152.0,88.0,4.466667,4.7,4.0,138.0,138.0,138.0,NaN,NaN,NaN,NaN,NaN,NaN,9.500000,9.9,9.1,47.500000,55.0,37.0,0.000000,2.0,-2.0,19.10,21.0,17.2,332.5,356.0,309.0,0.55,0.6,0.5,9.5,11.0,8.0,2.00,2.0,2.0,1.30,1.3,1.3,41.90,41.9,41.9,NaN,NaN,NaN,NaN,NaN,NaN,93.310345,101.0,83.0,99.907407,128.0,88.0,53.351852,74.0,39.0,65.689655,91.0,54.0,18.653846,28.0,8.0,37.547980,38.200001,35.900002,98.153846,100.0,95.0,2.786307,3.40249,2.11618,28.000000,80.0,0.0,NaN,NaN,NaN,15.409091,21.0,11.0,25.727273,35.0,22.0
1,7.352000,7.40,7.29,21.5,23.0,20.0,-2.400000,-1.0,-4.0,113.666667,119.0,107.0,1.246667,1.33,1.13,101.000000,131.0,67.0,3.720000,4.5,3.3,139.0,145.0,137.0,2.65,3.5,1.8,22.0,22.0,22.0,7.933333,9.9,6.7,39.800000,46.0,35.0,-2.400000,-1.0,-4.0,11.90,15.5,8.3,155.5,166.0,145.0,0.45,0.5,0.4,9.0,9.0,9.0,1.80,1.8,1.8,1.70,1.9,1.5,34.65,38.2,31.1,NaN,NaN,NaN,211.94445,350.00001,-64.166669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.181818,90.0,5.0,23.48,31.0,10.0,4.280000,14.0,-4.0,11.760000,20.0,4.0
2,7.377500,7.44,7.32,23.5,24.0,23.0,-1.500000,-1.0,-2.0,108.000000,110.0,106.0,1.136667,1.21,1.06,106.750000,127.0,98.0,3.933333,4.1,3.7,136.0,136.0,136.0,NaN,NaN,NaN,NaN,NaN,NaN,8.350000,8.9,7.8,41.000000,46.0,36.0,-1.500000,-1.0,-2.0,8.75,9.8,7.7,161.5,168.0,155.0,0.55,0.6,0.5,7.0,7.0,7.0,1.60,1.6,1.6,1.20,1.2,1.2,43.80,43.8,43.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.454545,70.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7.416250,7.46,7.28,24.0,24.0,24.0,-0.250000,0.0,-2.0,106.500000,109.0,104.0,1.060000,1.13,0.96,98.200000,130.0,69.0,3.975000,4.6,3.6,138.0,139.0,137.0,NaN,NaN,NaN,NaN,NaN,NaN,9.100000,9.6,8.6,36.625000,51.0,30.0,-0.250000,0.0,-2.0,26.40,34.7,18.1,231.5,241.0,222.0,0.65,0.7,0.6,15.0,15.0,15.0,1.95,2.1,1.8,1.65,1.8,1.5,39.85,47.8,31.9,NaN,NaN,NaN,375.00000,375.00000,375.000000,105.352941,123.0,83.0,121.676471,151.0,106.0,71.735294,87.0,49.0,87.647059,100.0,66.0,21.142857,29.0,12.0,37.003334,38.599998,35.400002,95.052632,100.0,86.0,4.057592,5.39267,3.45550,23.043478,60.0,0.0,NaN,NaN,NaN,21.161290,33.0,14.0,35.387097,49.0,25.0
4,7.333333,7.41,7.26,25.5,27.0,24.0,-1.428571,2.0,-5.0,105.000000,111.0,99.0,1.044000,1.15,0.90,105.976190,138.0,51.0,4.020000,4.6,3.1,138.0,143.0,133.0,NaN,NaN,NaN,NaN,NaN,NaN,11.400000,11.4,11.4,48.285714,63.0,41.0,-1.428571,2.0,-5.0,13.60,13.6,13.6,120.0,124.0,116.0,0.50,0.5,0.5,7.0,7.0,7.0,NaN,NaN,NaN,1.50,1.5,1.5,43.30,43.3,43.3,NaN,NaN,NaN,NaN,NaN,NaN,84.244444,101.0,73.0,102.173913,135.0,78.0,51.347826,70.0,37.0,66.800000,90.0,49.0,18.406250,24.0,12.0,37.245834,37.700001,36.200001,98.065217,100.0,95.0,3.679422,4.56044,3.07692,26.315789,80.0,0.0,NaN,NaN,NaN,12.133333,19.0,3.0,24.044444,36.0,17.0

In [167]:
# parsing infection

def inf_parser_abx(value, timeLimits=None):
    if value == np.NaN or pd.isna(value):
        return 0

    a = value.replace("'", '"')
    a = a.replace('\n ...\n',',').replace('\n', ',').replace('...', '')
    a = a.replace('": None', '": "None"')
    for valuename in ['antibiotic','antibiotic_time']:
        a = a.replace(f'), "{valuename}"', f')", "{valuename}"')
    a = json.loads(a)
    b = [(dt.datetime.strptime(i['suspected_infection_time'], '%Y-%m-%dT%H:%M:%S') if i['suspected_infection_time'] not in ("None", None) else np.NaN, 
          dt.datetime.strptime(i['antibiotic_time'], '%Y-%m-%dT%H:%M:%S') if i['antibiotic_time'] not in ("None", None) else np.NaN,
          i['antibiotic'] if i['antibiotic'] not in ("None", None) else np.NaN,
          i['specimen'], i['positiveculture']) for i in a]
    b = [i for i in b if not pd.isnull(i[1])]
    if timeLimits == None:
        inc_b = b.copy()
    else:
        inc_b = [i for i in b if not pd.isnull(i[1]) and timeLimits[0] <= i[1] <= timeLimits[1]]
    return len(list(set([i[2] for i in b])))

infList = []
for i in range(len(df['infection'])):
    y = inf_parser_abx(df['infection'][i], timeLimits=(df['postop_intime'][i].to_pydatetime(), df['postop_intime'][i].to_pydatetime() + dt.timedelta(hours=hoursRange)))
    infList.append(y)

dfForImpute['abx_no'] = infList
dfForImpute['abx_bool'] = (dfForImpute['abx_no'] > 0.5).astype('int')
dfForImpute['abx_no'] = dfForImpute['abx_no'].astype('category')
dfForImpute['abx_bool'] = dfForImpute['abx_bool'].astype('category')

In [168]:
# parsing aki

def aki_parser(value, timeLimits=None):
    if value == np.NaN or pd.isna(value):
        return {'creat':[np.NaN for i in range(4)], 'uo':[np.NaN for i in range(4)]}

    a = value.replace("'", '"')
    a = a.replace('\n ...\n',',').replace('\n', ',').replace('...', '')
    a = a.replace('": None', '": "None"')
    a = json.loads(a)
    b = [(dt.datetime.strptime(i['charttime'], '%Y-%m-%dT%H:%M:%S'),
          i['aki_stage_creat'] if i['aki_stage_creat'] not in ("None", None) else np.NaN,
          i['aki_stage_uo'] if i['aki_stage_uo'] not in ("None", None) else np.NaN) for i in a if i['charttime'] not in ('None', None)]
    
    if timeLimits == None:
        creat = [i[1] for i in b if not pd.isnull(i[1])]
        uo = [i[2] for i in b if not pd.isnull(i[2])]
    else:
        creat = [i[1] for i in b if not pd.isnull(i[1]) and timeLimits[0] <= i[0] <= timeLimits[1]]
        uo = [i[2] for i in b if not pd.isnull(i[2]) and timeLimits[0] <= i[0] <= timeLimits[1]]
    return {'creat':(sum(creat)/len(creat), max(creat), min(creat), sorted(creat)[0]) if len(creat)>0 else tuple([np.NaN for i in range(4)]),
            'uo':(sum(uo)/len(uo), max(uo), min(uo), sorted(uo)[0]) if len(uo)>0 else tuple([np.NaN for i in range(4)])}

creatList = []
uoList = []
for i in range(len(df['aki'])):
    y = aki_parser(df['aki'][i], timeLimits=(df['postop_intime'][i].to_pydatetime(), df['postop_intime'][i].to_pydatetime() + dt.timedelta(hours=hoursRange)))
    creatList.append(y['creat'][0])
    uoList.append(y['uo'][0])
dfForImpute['aki_stage_creat_mean'] = creatList
dfForImpute['aki_stage_creat_mean'] = dfForImpute['aki_stage_creat_mean'].astype('category')
dfForImpute['aki_stage_uo_mean'] = uoList
dfForImpute['aki_stage_uo_mean'] = dfForImpute['aki_stage_uo_mean'].astype('category')

In [169]:
# add on non-time data for imputation
# dfForImpute = dfForImpute.copy()
# extraColumns = [i for i in dfDroppedMissing.columns if i not in list(dfForImpute.columns) + timeseries + ['infection', 'vent_array', 'int_time1', 'ext_time1'] + ptinfo + adm_num]
# print(extraColumns)
# for i in extraColumns:
#     if i in ('weight', 'height', 'duration1','duration2'):
#         dfForImpute[i] = df[i]
#     else:
#         dfForImpute[i] = df[i].astype('category')
# dfForImpute = dfForImpute.copy()

dfForImpute.head(5)
extraColumns = [i for i in dfDroppedMissing.columns if i not in [*dfForImpute.columns.tolist(), 
                                                                 *timeseries, 
                                                                 *colCats['admInfo'], *colCats['admNum'], *colCats['admTime'], *colCats['diabUnits'],
                                                                 *colCats['ventTimes'], *colCats['readmitInfo'],
                                                                 'index', 'aki', 'vent_array', 'echo', 'fluid', 'infection', 'intropes',]]
for i in extraColumns:
    if i in ('weight', 'height', 'age'):
        dfForImpute[i] = df[i]
    else:
        dfForImpute[i] = df[i].astype('category')
dfForImpute = dfForImpute.copy()

In [170]:
# before imputation again
pd.set_option('display.max_rows', None)
print(dfForImpute.dtypes)
pd.reset_option('display.max_rows')

ph_mean                  float64
ph_max                   float64
ph_min                   float64
bicarb_mean              float64
bicarb_max               float64
bicarb_min               float64
baseexcess_mean          float64
baseexcess_max           float64
baseexcess_min           float64
chloride_mean            float64
chloride_max             float64
chloride_min             float64
free_calcium_mean        float64
free_calcium_max         float64
free_calcium_min         float64
glucose_mean             float64
glucose_max              float64
glucose_min              float64
potassium_mean           float64
potassium_max            float64
potassium_min            float64
sodium_mean              float64
sodium_max               float64
sodium_min               float64
lactate_mean             float64
lactate_max              float64
lactate_min              float64
hematocrit_mean          float64
hematocrit_max           float64
hematocrit_min           float64
hb_mean                  float64
hb_max                   float64
hb_min                   float64
pco2_mean                float64
pco2_max                 float64
pco2_min                 float64
po2_mean                 float64
po2_max                  float64
po2_min                  float64
wcc_mean                 float64
wcc_max                  float64
wcc_min                  float64
plt_mean                 float64
plt_max                  float64
plt_min                  float64
creatinine_mean          float64
creatinine_max           float64
creatinine_min           float64
bun_mean                 float64
bun_max                  float64
bun_min                  float64
magnesium_mean           float64
magnesium_max            float64
magnesium_min            float64
inr_mean                 float64
inr_max                  float64
inr_min                  float64
ptt_mean                 float64
ptt_max                  float64
ptt_min                  float64
hba1c_mean               float64
hba1c_max                float64
hba1c_min                float64
prbc_mean                float64
prbc_max                 float64
prbc_min                 float64
hr_mean                  float64
hr_max                   float64
hr_min                   float64
sbp_mean                 float64
sbp_max                  float64
sbp_min                  float64
dbp_mean                 float64
dbp_max                  float64
dbp_min                  float64
meanbp_mean              float64
meanbp_max               float64
meanbp_min               float64
rr_mean                  float64
rr_max                   float64
rr_min                   float64
temp_mean                float64
temp_max                 float64
temp_min                 float64
spo2_mean                float64
spo2_max                 float64
spo2_min                 float64
cardiac_index_mean       float64
cardiac_index_max        float64
cardiac_index_min        float64
dtoutput_mean            float64
dtoutput_max             float64
dtoutput_min             float64
pasp_mean                float64
pasp_max                 float64
pasp_min                 float64
padp_mean                float64
padp_max                 float64
padp_min                 float64
mpap_mean                float64
mpap_max                 float64
mpap_min                 float64
abx_no                  category
abx_bool                category
aki_stage_creat_mean    category
aki_stage_uo_mean       category
age                        int64
gender                  category
ethnicity               category
height                   float64
weight                   float64
admission_type          category
admission_location      category
insurance               category
marital_status          category
language                category
first_careunit          category
last_careunit           category
dbsource                category
sofa                    category
cabg                    category
aortic                  category
mitral                  category
tricuspid               category
pulmonary               category
mi                      category
arrhythmia              category
ccf                     category
pvd                     category
cvd                     category
dementia                category
copd                    category
rheum                   category
pud                     category
liver_mild              category
t1dm                    category
t2dm                    category
paraplegia              category
ckd                     category
malig                   category
liver_severe            category
met_ca                  category
aids                    category
smoking                 category
reintubation            category
dtype: object

In [ ]:
dfForImpute2 = dfForImpute[[i for i in dfForImpute.columns]]

kds = mf.ImputationKernel(
  dfForImpute2,
  datasets=1,
  save_all_iterations=True,
  random_state=1991
)

# Run the MICE algorithm for 3 iterations
kds.mice(3)

print(kds)

dfImputed = kds.complete_data(dataset=0, inplace=False)
print(dfImputed.isnull().sum(0))

# after imputation
dfImputed.head(10)

In [ ]:
y = np.asarray([i.to_pydatetime() for i in df["postop_intime"]])
z = np.asarray([i.to_pydatetime() for i in df["outtime"]])
dfImputed['icu_stay_hrs'] = [i.total_seconds()/3600 for i in z-y]
# dfImputed[[i for i in adm_num if i != 'reint_time']] = df[[i for i in adm_num if i != 'reint_time']] #marcel
dfImputed[colCats['admInfo']] = df[colCats['admInfo']]
dfImputed[colCats['admTime']] = df[colCats['admTime']]
dfImputed[colCats['admNum']] = df[colCats['admNum']]
dfImputed[colCats['ventTimes']] = df[colCats['ventTimes']]
dfImputed[colCats['readmitInfo']] = df[colCats['readmitInfo']]
dfImputed.head(5)

In [ ]:
dfImputed.to_csv('imputedReadmission.csv')